### ISSUE TITLE
Accept `datetime.date` as X input

### ISSUE THREAD

**Issue by acarl005** [tammoippen/plotille#26]
For time series plotting, python's built in `datetime.datetime` class is much appreciated! However, sometimes `datetime.date` is more convenient. Could these be accepted as input as well?

**Comment by tammoippen** [comment]
Hi @acarl005 , Thanks for the suggestion. I guess, it will be done by creating and registering a formatter and converter to [`InputFormatter`](https://github.com/tammoippen/plotille/blob/master/plotille/_input_formatter.py#L35), similar to the `datetime` converter/formatter. Are you interested in providing a PR? Otherwise I will look into this, but it might take some weeks for me to find the time.

**Comment by acarl005** [comment]
Sure! I'd be happy to add. Can you show me how to trigger the test suite?

**Comment by tammoippen** [comment]
You can also look at the ci script: https://github.com/tammoippen/plotille/blob/master/.circleci/config.yml

Espacially `commands: tester:`

**Comment by acarl005** [comment]
Thanks! Check out #28 and see what you think of this implementation.

**Comment by tammoippen** [comment]
Closing as of #28
