### ISSUE TITLE
Draw vertical or horizontal lines on plots

### ISSUE THREAD

**Issue by acarl005** [tammoippen/plotille#27]
Drawing arbitrary vertical or horizontal lines on plot (scatter plots or histograms) is generally very useful, something analogous to [this in matplotlib](https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.axes.Axes.axvline.html).

**Comment by tammoippen** [comment]
Hello @acarl005, thanks for the suggestion. I think they can easily be implemented in [`Figure`](https://github.com/tammoippen/plotille/blob/master/plotille/_figure.py) by adding a methods, that use the [`plot`](https://github.com/tammoippen/plotille/blob/master/plotille/_figure.py#L241)  function with two coordinates in X and Y, respectively. Are you interested in providing a PR? Otherwise I will look into this, but it might take some weeks for me to find the time.

**Comment by acarl005** [comment]
For the API, what did you have in mind? If I wanted to create a vertical line at x = 5, maybe something like `fig.plot(X=5)` where `Y` argument is omitted?

**Comment by tammoippen** [comment]
I think, i would prefer a new function for each, `vline(x)` and `hline(y)`.

**Comment by tammoippen** [comment]
Implemented in #38. Closing
