### ISSUE TITLE
Windows 10 terminal does not display brailles

### ISSUE THREAD

**Issue by benbensenton** [tammoippen/plotille#48]
running the sample code in a win 10 terminal window shows the attached outcome, whereas running the same code in eg. pycharms terminal works as described

![Screenshot 2022-03-26 020755](https://user-images.githubusercontent.com/93262658/160227158-186f40d8-89a3-4fec-9c7c-dff95df58440.png)

**Comment by tammoippen** [comment]
Hi @benbensenton ,

which win 10 terminal are you using exactly? CMD, Powershell, or the new [microsoft terminal](https://github.com/Microsoft/Terminal)? They all have different capabilities..

here you actually have two issues:

- the unicode braille characters are not displayed. This can usually be fixed by using a monospaced font, that can display them, eg https://github.com/tonsky/FiraCode or most from 
https://github.com/ryanoasis/nerd-fonts Do the trick
- the ansi color codes are not interpreted (eg `esc[38;5;25m`). This is usually closely tight to the terminal you are using. Maybe you have some luck using [colorama](https://pypi.org/project/colorama/) with your code - for the basic ansi color codes this should work. Or you try a different terminal?

Best tammo

**Comment by benbensenton** [comment]
thank you @tammoippen ,
 i tried a lot of fonts, fira code, cascadia code and many other monospaced fonts, the one working (displaying the glyphs and colors correctly) was Iosevca Term, https://github.com/be5invis/Iosevka/blob/v15.1.0/doc/PACKAGE-LIST.md
thanks ben
