### ISSUE TITLE
[Feature request] support arrow

### ISSUE THREAD

**Issue by feizheng10** [tammoippen/plotille#50]
Would you consider to support basic arrow as a start/end point of line just for convenience?
Or can we draw " -----------> " easily?

**Comment by tammoippen** [comment]
This only works well with horizontal and vertical lines, right. Otherwise you need the pointy end at an angle. 

When you only want horizontal arrows, you could write a text into the canvas:

```py
fig.text([0.5], [0.5], ["----------->"])
```

for horizontal lines, you could write each character at a time, but then you need to consider the height of one character, ie set canvas height and max/min y values and you know the delta-y for a character. Then:

``py
fig.text(xs, ys, ["^", "|", "|", "|", "|", "|", …])
```

**Comment by feizheng10** [comment]
Thanks for your quick responds!!
It is good enough for my usage for now.
